using EksamensProjektScooterLandBlazor.Shared.Models;

namespace EksamensProjektScooterLandBlazor.Server.SeedData
{
    public class SeedDataPostnummer
    {

        public SeedDataPostnummer() { }

        public void SeedPostnummer()
        {
            var postNummerList = new List<PostNummerOgBy>
            {
                new PostNummerOgBy { Postnummer = 1000, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1050, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1100, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1200, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1250, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1300, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1350, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1400, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1450, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1500, ByNavn = "København K" },
                new PostNummerOgBy { Postnummer = 1550, ByNavn = "København V" },
                new PostNummerOgBy { Postnummer = 1600, ByNavn = "København V" },
                new PostNummerOgBy { Postnummer = 1650, ByNavn = "København V" },
                new PostNummerOgBy { Postnummer = 1700, ByNavn = "København V" },
                new PostNummerOgBy { Postnummer = 1750, ByNavn = "København V" },
                new PostNummerOgBy { Postnummer = 1800, ByNavn = "Frederiksberg C" },
                new PostNummerOgBy { Postnummer = 1850, ByNavn = "Frederiksberg C" },
                new PostNummerOgBy { Postnummer = 1900, ByNavn = "Frederiksberg C" },
                new PostNummerOgBy { Postnummer = 1950, ByNavn = "Frederiksberg C" },
                new PostNummerOgBy { Postnummer = 2000, ByNavn = "Frederiksberg" },
                new PostNummerOgBy { Postnummer = 2100, ByNavn = "København Ø" },
                new PostNummerOgBy { Postnummer = 2150, ByNavn = "Nordhavn" },
                new PostNummerOgBy { Postnummer = 2200, ByNavn = "København N" },
                new PostNummerOgBy { Postnummer = 2300, ByNavn = "København S" },
                new PostNummerOgBy { Postnummer = 2400, ByNavn = "København NV" },
                new PostNummerOgBy { Postnummer = 2450, ByNavn = "København SV" },
                new PostNummerOgBy { Postnummer = 2500, ByNavn = "Valby" },
                new PostNummerOgBy { Postnummer = 2600, ByNavn = "Glostrup" },
                new PostNummerOgBy { Postnummer = 2620, ByNavn = "Albertslund" },
                new PostNummerOgBy { Postnummer = 2630, ByNavn = "Taastrup" },
                new PostNummerOgBy { Postnummer = 2640, ByNavn = "Hedehusene" },
                new PostNummerOgBy { Postnummer = 2650, ByNavn = "Hvidovre" },
                new PostNummerOgBy { Postnummer = 2660, ByNavn = "Brøndby Strand" },
                new PostNummerOgBy { Postnummer = 2665, ByNavn = "Vallensbæk Strand" },
                new PostNummerOgBy { Postnummer = 2670, ByNavn = "Greve" },
                new PostNummerOgBy { Postnummer = 2680, ByNavn = "Solrød Strand" },
                new PostNummerOgBy { Postnummer = 2690, ByNavn = "Karise" },
                new PostNummerOgBy { Postnummer = 2700, ByNavn = "Brønshøj" },
                new PostNummerOgBy { Postnummer = 2720, ByNavn = "Vanløse" },
                new PostNummerOgBy { Postnummer = 2730, ByNavn = "Herlev" },
                new PostNummerOgBy { Postnummer = 2740, ByNavn = "Skovlunde" },
                new PostNummerOgBy { Postnummer = 2750, ByNavn = "Ballerup" },
                new PostNummerOgBy { Postnummer = 2760, ByNavn = "Måløv" },
                new PostNummerOgBy { Postnummer = 2770, ByNavn = "Kastrup" },
                new PostNummerOgBy { Postnummer = 2791, ByNavn = "Dragør" },
                new PostNummerOgBy { Postnummer = 2800, ByNavn = "Kongens Lyngby" },
                new PostNummerOgBy { Postnummer = 2820, ByNavn = "Gentofte" },
                new PostNummerOgBy { Postnummer = 2830, ByNavn = "Virum" },
                new PostNummerOgBy { Postnummer = 2840, ByNavn = "Holte" },
                new PostNummerOgBy { Postnummer = 2850, ByNavn = "Nærum" },
                new PostNummerOgBy { Postnummer = 2860, ByNavn = "Søborg" },
                new PostNummerOgBy { Postnummer = 2870, ByNavn = "Dyssegård" },
                new PostNummerOgBy { Postnummer = 2880, ByNavn = "Bagsværd" },
                new PostNummerOgBy { Postnummer = 2900, ByNavn = "Hellerup" },
                new PostNummerOgBy { Postnummer = 2920, ByNavn = "Charlottenlund" },
                new PostNummerOgBy { Postnummer = 2930, ByNavn = "Klampenborg" },
                new PostNummerOgBy { Postnummer = 2942, ByNavn = "Skodsborg" },
                new PostNummerOgBy { Postnummer = 2950, ByNavn = "Vedbæk" },
                new PostNummerOgBy { Postnummer = 2960, ByNavn = "Rungsted Kyst" },
                new PostNummerOgBy { Postnummer = 2970, ByNavn = "Hørsholm" },
                new PostNummerOgBy { Postnummer = 2980, ByNavn = "Kokkedal" },
                new PostNummerOgBy { Postnummer = 2990, ByNavn = "Nivå" },
                new PostNummerOgBy { Postnummer = 3000, ByNavn = "Helsingør" },
                new PostNummerOgBy { Postnummer = 3050, ByNavn = "Humlebæk" },
                new PostNummerOgBy { Postnummer = 3060, ByNavn = "Espergærde" },
                new PostNummerOgBy { Postnummer = 3070, ByNavn = "Snekkersten" },
                new PostNummerOgBy { Postnummer = 3080, ByNavn = "Tikøb" },
                new PostNummerOgBy { Postnummer = 3100, ByNavn = "Hornbæk" },
                new PostNummerOgBy { Postnummer = 3120, ByNavn = "Dronningmølle" },
                new PostNummerOgBy { Postnummer = 3140, ByNavn = "Ålsgårde" },
                new PostNummerOgBy { Postnummer = 3150, ByNavn = "Hellebæk" },
                new PostNummerOgBy { Postnummer = 3200, ByNavn = "Helsinge" },
                new PostNummerOgBy { Postnummer = 3210, ByNavn = "Vejby" },
                new PostNummerOgBy { Postnummer = 3220, ByNavn = "Tisvildeleje" },
                new PostNummerOgBy { Postnummer = 3230, ByNavn = "Græsted" },
                new PostNummerOgBy { Postnummer = 3250, ByNavn = "Gilleleje" },
                new PostNummerOgBy { Postnummer = 3300, ByNavn = "Frederiksværk" },
                new PostNummerOgBy { Postnummer = 3310, ByNavn = "Ølsted" },
                new PostNummerOgBy { Postnummer = 3320, ByNavn = "Skævinge" },
                new PostNummerOgBy { Postnummer = 3330, ByNavn = "Gørløse" },
                new PostNummerOgBy { Postnummer = 3360, ByNavn = "Liseleje" },
                new PostNummerOgBy { Postnummer = 3370, ByNavn = "Melby" },
                new PostNummerOgBy { Postnummer = 3390, ByNavn = "Hundested" },
                new PostNummerOgBy { Postnummer = 3400, ByNavn = "Hillerød" },
                new PostNummerOgBy { Postnummer = 3450, ByNavn = "Allerød" },
                new PostNummerOgBy { Postnummer = 3460, ByNavn = "Birkerød" },
                new PostNummerOgBy { Postnummer = 3480, ByNavn = "Fredensborg" },
                new PostNummerOgBy { Postnummer = 3490, ByNavn = "Kvistgård" },
                new PostNummerOgBy { Postnummer = 3500, ByNavn = "Værløse" },
                new PostNummerOgBy { Postnummer = 3520, ByNavn = "Farum" },
                new PostNummerOgBy { Postnummer = 3540, ByNavn = "Lynge" },
                new PostNummerOgBy { Postnummer = 3550, ByNavn = "Slangerup" },
                new PostNummerOgBy { Postnummer = 3600, ByNavn = "Frederikssund" },
                new PostNummerOgBy { Postnummer = 3630, ByNavn = "Jægerspris" },
                new PostNummerOgBy { Postnummer = 3650, ByNavn = "Ølstykke" },
                new PostNummerOgBy { Postnummer = 3660, ByNavn = "Stenløse" },
                new PostNummerOgBy { Postnummer = 3670, ByNavn = "Veksø Sjælland" },
                new PostNummerOgBy { Postnummer = 4000, ByNavn = "Roskilde" },
                new PostNummerOgBy { Postnummer = 4040, ByNavn = "Jyllinge" },
                new PostNummerOgBy { Postnummer = 4050, ByNavn = "Skibby" },
                new PostNummerOgBy { Postnummer = 4060, ByNavn = "Kirke Såby" },
                new PostNummerOgBy { Postnummer = 4070, ByNavn = "Kirke Hyllinge" },
                new PostNummerOgBy { Postnummer = 4100, ByNavn = "Ringsted" },
                new PostNummerOgBy { Postnummer = 4130, ByNavn = "Viby Sjælland" },
                new PostNummerOgBy { Postnummer = 4140, ByNavn = "Borup" },
                new PostNummerOgBy { Postnummer = 4160, ByNavn = "Herlufmagle" },
                new PostNummerOgBy { Postnummer = 4171, ByNavn = "Glumsø" },
                new PostNummerOgBy { Postnummer = 4173, ByNavn = "Fjenneslev" },
                new PostNummerOgBy { Postnummer = 4174, ByNavn = "Jystrup Midtsj" },
                new PostNummerOgBy { Postnummer = 4180, ByNavn = "Sorø" },
                new PostNummerOgBy { Postnummer = 4190, ByNavn = "Munke Bjergby" },
                new PostNummerOgBy { Postnummer = 4200, ByNavn = "Slagelse" },
                new PostNummerOgBy { Postnummer = 4220, ByNavn = "Korsør" },
                new PostNummerOgBy { Postnummer = 4230, ByNavn = "Skælskør" },
                new PostNummerOgBy { Postnummer = 4241, ByNavn = "Vemmelev" },
                new PostNummerOgBy { Postnummer = 4242, ByNavn = "Boeslunde" },
                new PostNummerOgBy { Postnummer = 4243, ByNavn = "Rude" },
                new PostNummerOgBy { Postnummer = 4250, ByNavn = "Fuglebjerg" },
                new PostNummerOgBy { Postnummer = 4261, ByNavn = "Dalmose" },
                new PostNummerOgBy { Postnummer = 4262, ByNavn = "Sandved" },
                new PostNummerOgBy { Postnummer = 4270, ByNavn = "Høng" },
                new PostNummerOgBy { Postnummer = 4281, ByNavn = "Gørlev" },
                new PostNummerOgBy { Postnummer = 4291, ByNavn = "Ruds Vedby" },
                new PostNummerOgBy { Postnummer = 4293, ByNavn = "Dianalund" },
                new PostNummerOgBy { Postnummer = 4295, ByNavn = "Stenlille" },
                new PostNummerOgBy { Postnummer = 4296, ByNavn = "Nyrup" },
                new PostNummerOgBy { Postnummer = 4300, ByNavn = "Holbæk" },
                new PostNummerOgBy { Postnummer = 4320, ByNavn = "Lejre" },
                new PostNummerOgBy { Postnummer = 4330, ByNavn = "Hvalsø" },
                new PostNummerOgBy { Postnummer = 4340, ByNavn = "Tølløse" },
                new PostNummerOgBy { Postnummer = 4350, ByNavn = "Ugerløse" },
                new PostNummerOgBy { Postnummer = 4360, ByNavn = "Kirke Eskilstrup" },
                new PostNummerOgBy { Postnummer = 4370, ByNavn = "Store Merløse" },
                new PostNummerOgBy { Postnummer = 4390, ByNavn = "Vipperød" },
                new PostNummerOgBy { Postnummer = 4400, ByNavn = "Kalundborg" },
                new PostNummerOgBy { Postnummer = 4420, ByNavn = "Regstrup" },
                new PostNummerOgBy { Postnummer = 4440, ByNavn = "Mørkøv" },
                new PostNummerOgBy { Postnummer = 4450, ByNavn = "Jyderup" },
                new PostNummerOgBy { Postnummer = 4460, ByNavn = "Snertinge" },
                new PostNummerOgBy { Postnummer = 4470, ByNavn = "Svebølle" },
                new PostNummerOgBy { Postnummer = 4480, ByNavn = "Store Fuglede" },
                new PostNummerOgBy { Postnummer = 4490, ByNavn = "Jerslev Sjælland" },
                new PostNummerOgBy { Postnummer = 4500, ByNavn = "Nykøbing Sjælland" },
                new PostNummerOgBy { Postnummer = 4520, ByNavn = "Svinninge" },
                new PostNummerOgBy { Postnummer = 4532, ByNavn = "Gislinge" },
                new PostNummerOgBy { Postnummer = 4534, ByNavn = "Hørve" },
                new PostNummerOgBy { Postnummer = 4540, ByNavn = "Fårevejle" },
                new PostNummerOgBy { Postnummer = 4550, ByNavn = "Asnæs" },
                new PostNummerOgBy { Postnummer = 4560, ByNavn = "Vig" },
                new PostNummerOgBy { Postnummer = 4571, ByNavn = "Grevinge" },
                new PostNummerOgBy { Postnummer = 4572, ByNavn = "Nørre Asmindrup" },
                new PostNummerOgBy { Postnummer = 4573, ByNavn = "Højby" },
                new PostNummerOgBy { Postnummer = 4581, ByNavn = "Rørvig" },
                new PostNummerOgBy { Postnummer = 4583, ByNavn = "Sjællands Odde" },
                new PostNummerOgBy { Postnummer = 4591, ByNavn = "Føllenslev" },
                new PostNummerOgBy { Postnummer = 4592, ByNavn = "Sejerø" },
                new PostNummerOgBy { Postnummer = 4593, ByNavn = "Eskebjerg" },
                new PostNummerOgBy { Postnummer = 4600, ByNavn = "Køge" },
                new PostNummerOgBy { Postnummer = 4621, ByNavn = "Gadstrup" },
                new PostNummerOgBy { Postnummer = 4622, ByNavn = "Havdrup" },
                new PostNummerOgBy { Postnummer = 4623, ByNavn = "Lille Skensved" },
                new PostNummerOgBy { Postnummer = 4632, ByNavn = "Bjæverskov" },
                new PostNummerOgBy { Postnummer = 4640, ByNavn = "Faxe" },
                new PostNummerOgBy { Postnummer = 4652, ByNavn = "Hårlev" },
                new PostNummerOgBy { Postnummer = 4653, ByNavn = "Karise" },
                new PostNummerOgBy { Postnummer = 4654, ByNavn = "Faxe Ladeplads" },
                new PostNummerOgBy { Postnummer = 4660, ByNavn = "Store Heddinge" },
                new PostNummerOgBy { Postnummer = 4671, ByNavn = "Strøby" },
                new PostNummerOgBy { Postnummer = 4672, ByNavn = "Klippinge" },
                new PostNummerOgBy { Postnummer = 4673, ByNavn = "Rødvig Stevns" },
                new PostNummerOgBy { Postnummer = 4681, ByNavn = "Herfølge" },
                new PostNummerOgBy { Postnummer = 4682, ByNavn = "Tureby" },
                new PostNummerOgBy { Postnummer = 4683, ByNavn = "Rønnede" },
                new PostNummerOgBy { Postnummer = 4684, ByNavn = "Holmegaard" },
                new PostNummerOgBy { Postnummer = 4690, ByNavn = "Haslev" },
                new PostNummerOgBy { Postnummer = 4700, ByNavn = "Næstved" },
                new PostNummerOgBy { Postnummer = 4733, ByNavn = "Tappernøje" },
                new PostNummerOgBy { Postnummer = 4735, ByNavn = "Mern" },
                new PostNummerOgBy { Postnummer = 4736, ByNavn = "Karrebæksminde" },
                new PostNummerOgBy { Postnummer = 4750, ByNavn = "Lundby" },
                new PostNummerOgBy { Postnummer = 4760, ByNavn = "Vordingborg" },
                new PostNummerOgBy { Postnummer = 4771, ByNavn = "Kalvehave" },
                new PostNummerOgBy { Postnummer = 4772, ByNavn = "Langebæk" },
                new PostNummerOgBy { Postnummer = 4773, ByNavn = "Stensved" },
                new PostNummerOgBy { Postnummer = 4780, ByNavn = "Stege" },
                new PostNummerOgBy { Postnummer = 4791, ByNavn = "Borre" },
                new PostNummerOgBy { Postnummer = 4792, ByNavn = "Askeby" },
                new PostNummerOgBy { Postnummer = 4793, ByNavn = "Bogø By" },
                new PostNummerOgBy { Postnummer = 4800, ByNavn = "Nykøbing Falster" },
                new PostNummerOgBy { Postnummer = 4840, ByNavn = "Nørre Alslev" },
                new PostNummerOgBy { Postnummer = 4850, ByNavn = "Stubbekøbing" },
                new PostNummerOgBy { Postnummer = 4862, ByNavn = "Guldborg" },
                new PostNummerOgBy { Postnummer = 4863, ByNavn = "Eskilstrup" },
                new PostNummerOgBy { Postnummer = 4871, ByNavn = "Horbelev" },
                new PostNummerOgBy { Postnummer = 4872, ByNavn = "Idestrup" },
                new PostNummerOgBy { Postnummer = 4873, ByNavn = "Væggerløse" },
                new PostNummerOgBy { Postnummer = 4874, ByNavn = "Gedser" },
                new PostNummerOgBy { Postnummer = 4880, ByNavn = "Nysted" },
                new PostNummerOgBy { Postnummer = 4891, ByNavn = "Toreby L" },
                new PostNummerOgBy { Postnummer = 4892, ByNavn = "Kettinge" },
                new PostNummerOgBy { Postnummer = 4894, ByNavn = "Øster Ulslev" },
                new PostNummerOgBy { Postnummer = 4900, ByNavn = "Nakskov" },
                new PostNummerOgBy { Postnummer = 4912, ByNavn = "Harpelunde" },
                new PostNummerOgBy { Postnummer = 4913, ByNavn = "Horslunde" },
                new PostNummerOgBy { Postnummer = 4920, ByNavn = "Søllested" },
                new PostNummerOgBy { Postnummer = 4930, ByNavn = "Maribo" },
                new PostNummerOgBy { Postnummer = 4941, ByNavn = "Bandholm" },
                new PostNummerOgBy { Postnummer = 4943, ByNavn = "Torrig L" },
                new PostNummerOgBy { Postnummer = 4944, ByNavn = "Fejø" },
                new PostNummerOgBy { Postnummer = 4951, ByNavn = "Nørreballe" },
                new PostNummerOgBy { Postnummer = 4952, ByNavn = "Stokkemarke" },
                new PostNummerOgBy { Postnummer = 4953, ByNavn = "Vesterborg" },
                new PostNummerOgBy { Postnummer = 4960, ByNavn = "Holeby" },
                new PostNummerOgBy { Postnummer = 4970, ByNavn = "Rødby" },
                new PostNummerOgBy { Postnummer = 4983, ByNavn = "Dannemare" },
                new PostNummerOgBy { Postnummer = 4990, ByNavn = "Sakskøbing" },
                new PostNummerOgBy { Postnummer = 5000, ByNavn = "Odense C" },
                new PostNummerOgBy { Postnummer = 5200, ByNavn = "Odense V" },
                new PostNummerOgBy { Postnummer = 5210, ByNavn = "Odense NV" },
                new PostNummerOgBy { Postnummer = 5220, ByNavn = "Odense SØ" },
                new PostNummerOgBy { Postnummer = 5230, ByNavn = "Odense M" },
                new PostNummerOgBy { Postnummer = 5240, ByNavn = "Odense NØ" },
                new PostNummerOgBy { Postnummer = 5250, ByNavn = "Odense SV" },
                new PostNummerOgBy { Postnummer = 5260, ByNavn = "Odense S" },
                new PostNummerOgBy { Postnummer = 5270, ByNavn = "Odense N" },
                new PostNummerOgBy { Postnummer = 5290, ByNavn = "Marslev" },
                new PostNummerOgBy { Postnummer = 5300, ByNavn = "Kerteminde" },
                new PostNummerOgBy { Postnummer = 5320, ByNavn = "Agedrup" },
                new PostNummerOgBy { Postnummer = 5330, ByNavn = "Munkebo" },
                new PostNummerOgBy { Postnummer = 5350, ByNavn = "Rynkeby" },
                new PostNummerOgBy { Postnummer = 5370, ByNavn = "Mesinge" },
                new PostNummerOgBy { Postnummer = 5380, ByNavn = "Dalby" },
                new PostNummerOgBy { Postnummer = 5390, ByNavn = "Martofte" },
                new PostNummerOgBy { Postnummer = 5400, ByNavn = "Bogense" },
                new PostNummerOgBy { Postnummer = 5450, ByNavn = "Otterup" },
                new PostNummerOgBy { Postnummer = 5462, ByNavn = "Morud" },
                new PostNummerOgBy { Postnummer = 5463, ByNavn = "Harndrup" },
                new PostNummerOgBy { Postnummer = 5464, ByNavn = "Brenderup Fyn" },
                new PostNummerOgBy { Postnummer = 5466, ByNavn = "Asperup" },
                new PostNummerOgBy { Postnummer = 5471, ByNavn = "Søndersø" },
                new PostNummerOgBy { Postnummer = 5474, ByNavn = "Veflinge" },
                new PostNummerOgBy { Postnummer = 5485, ByNavn = "Skamby" },
                new PostNummerOgBy { Postnummer = 5491, ByNavn = "Blommenslyst" },
                new PostNummerOgBy { Postnummer = 5492, ByNavn = "Vissenbjerg" },
                new PostNummerOgBy { Postnummer = 5500, ByNavn = "Middelfart" },
                new PostNummerOgBy { Postnummer = 5540, ByNavn = "Ullerslev" },
                new PostNummerOgBy { Postnummer = 5550, ByNavn = "Langeskov" },
                new PostNummerOgBy { Postnummer = 5560, ByNavn = "Aarup" },
                new PostNummerOgBy { Postnummer = 5580, ByNavn = "Nørre Aaby" },
                new PostNummerOgBy { Postnummer = 5591, ByNavn = "Gelsted" },
                new PostNummerOgBy { Postnummer = 5592, ByNavn = "Ejby" },
                new PostNummerOgBy { Postnummer = 5600, ByNavn = "Faaborg" },
                new PostNummerOgBy { Postnummer = 5610, ByNavn = "Assens" },
                new PostNummerOgBy { Postnummer = 5620, ByNavn = "Glamsbjerg" },
                new PostNummerOgBy { Postnummer = 5631, ByNavn = "Ebberup" },
                new PostNummerOgBy { Postnummer = 5642, ByNavn = "Millinge" },
                new PostNummerOgBy { Postnummer = 5672, ByNavn = "Broby" },
                new PostNummerOgBy { Postnummer = 5683, ByNavn = "Haarby" },
                new PostNummerOgBy { Postnummer = 5690, ByNavn = "Tommerup" },
                new PostNummerOgBy { Postnummer = 5700, ByNavn = "Svendborg" },
                new PostNummerOgBy { Postnummer = 5750, ByNavn = "Ringe" },
                new PostNummerOgBy { Postnummer = 5762, ByNavn = "Vester Skerninge" },
                new PostNummerOgBy { Postnummer = 5771, ByNavn = "Stenstrup" },
                new PostNummerOgBy { Postnummer = 5772, ByNavn = "Kværndrup" },
                new PostNummerOgBy { Postnummer = 5792, ByNavn = "Årslev" },
                new PostNummerOgBy { Postnummer = 5800, ByNavn = "Nyborg" },
                new PostNummerOgBy { Postnummer = 5853, ByNavn = "Ørbæk" },
                new PostNummerOgBy { Postnummer = 5854, ByNavn = "Gislev" },
                new PostNummerOgBy { Postnummer = 5856, ByNavn = "Ryslinge" },
                new PostNummerOgBy { Postnummer = 5863, ByNavn = "Ferritslev Fyn" },
                new PostNummerOgBy { Postnummer = 5871, ByNavn = "Frørup" },
                new PostNummerOgBy { Postnummer = 5874, ByNavn = "Hesselager" },
                new PostNummerOgBy { Postnummer = 5881, ByNavn = "Skårup Fyn" },
                new PostNummerOgBy { Postnummer = 5882, ByNavn = "Vejstrup" },
                new PostNummerOgBy { Postnummer = 5883, ByNavn = "Oure" },
                new PostNummerOgBy { Postnummer = 5884, ByNavn = "Gudme" },
                new PostNummerOgBy { Postnummer = 5892, ByNavn = "Gudbjerg Sydfyn" },
                new PostNummerOgBy { Postnummer = 5900, ByNavn = "Rudkøbing" },
                new PostNummerOgBy { Postnummer = 5932, ByNavn = "Humble" },
                new PostNummerOgBy { Postnummer = 5935, ByNavn = "Bagenkop" },
                new PostNummerOgBy { Postnummer = 5953, ByNavn = "Tranekær" },
                new PostNummerOgBy { Postnummer = 5960, ByNavn = "Marstal" },
                new PostNummerOgBy { Postnummer = 5970, ByNavn = "Ærøskøbing" },
                new PostNummerOgBy { Postnummer = 5985, ByNavn = "Søby Ærø" },
                new PostNummerOgBy { Postnummer = 6000, ByNavn = "Kolding" },
                new PostNummerOgBy { Postnummer = 6040, ByNavn = "Egtved" },
                new PostNummerOgBy { Postnummer = 6051, ByNavn = "Almind" },
                new PostNummerOgBy { Postnummer = 6052, ByNavn = "Viuf" },
                new PostNummerOgBy { Postnummer = 6064, ByNavn = "Jordrup" },
                new PostNummerOgBy { Postnummer = 6070, ByNavn = "Christiansfeld" },
                new PostNummerOgBy { Postnummer = 6091, ByNavn = "Bjert" },
                new PostNummerOgBy { Postnummer = 6092, ByNavn = "Sønder Stenderup" },
                new PostNummerOgBy { Postnummer = 6093, ByNavn = "Sjølund" },
                new PostNummerOgBy { Postnummer = 6094, ByNavn = "Hejls" },
                new PostNummerOgBy { Postnummer = 6100, ByNavn = "Haderslev" },
                new PostNummerOgBy { Postnummer = 6200, ByNavn = "Aabenraa" },
                new PostNummerOgBy { Postnummer = 6230, ByNavn = "Rødekro" },
                new PostNummerOgBy { Postnummer = 6240, ByNavn = "Løgumkloster" },
                new PostNummerOgBy { Postnummer = 6261, ByNavn = "Bredebro" },
                new PostNummerOgBy { Postnummer = 6270, ByNavn = "Tønder" },
                new PostNummerOgBy { Postnummer = 6280, ByNavn = "Højer" },
                new PostNummerOgBy { Postnummer = 6300, ByNavn = "Gråsten" },
                new PostNummerOgBy { Postnummer = 6310, ByNavn = "Broager" },
                new PostNummerOgBy { Postnummer = 6320, ByNavn = "Egernsund" },
                new PostNummerOgBy { Postnummer = 6330, ByNavn = "Padborg" },
                new PostNummerOgBy { Postnummer = 6340, ByNavn = "Kruså" },
                new PostNummerOgBy { Postnummer = 6360, ByNavn = "Tinglev" },
                new PostNummerOgBy { Postnummer = 6372, ByNavn = "Bylderup-Bov" },
                new PostNummerOgBy { Postnummer = 6392, ByNavn = "Bolderslev" },
                new PostNummerOgBy { Postnummer = 6400, ByNavn = "Sønderborg" },
                new PostNummerOgBy { Postnummer = 6430, ByNavn = "Nordborg" },
                new PostNummerOgBy { Postnummer = 6440, ByNavn = "Augustenborg" },
                new PostNummerOgBy { Postnummer = 6470, ByNavn = "Sydals" },
                new PostNummerOgBy { Postnummer = 6500, ByNavn = "Vojens" },
                new PostNummerOgBy { Postnummer = 6510, ByNavn = "Gram" },
                new PostNummerOgBy { Postnummer = 6520, ByNavn = "Toftlund" },
                new PostNummerOgBy { Postnummer = 6534, ByNavn = "Agerskov" },
                new PostNummerOgBy { Postnummer = 6535, ByNavn = "Branderup J" },
                new PostNummerOgBy { Postnummer = 6541, ByNavn = "Bevtoft" },
                new PostNummerOgBy { Postnummer = 6560, ByNavn = "Sommersted" },
                new PostNummerOgBy { Postnummer = 6580, ByNavn = "Vamdrup" },
                new PostNummerOgBy { Postnummer = 6600, ByNavn = "Vejen" },
                new PostNummerOgBy { Postnummer = 6621, ByNavn = "Gesten" },
                new PostNummerOgBy { Postnummer = 6622, ByNavn = "Bække" },
                new PostNummerOgBy { Postnummer = 6623, ByNavn = "Vorbasse" },
                new PostNummerOgBy { Postnummer = 6630, ByNavn = "Rødding" },
                new PostNummerOgBy { Postnummer = 6640, ByNavn = "Lunderskov" },
                new PostNummerOgBy { Postnummer = 6650, ByNavn = "Brørup" },
                new PostNummerOgBy { Postnummer = 6660, ByNavn = "Lintrup" },
                new PostNummerOgBy { Postnummer = 6670, ByNavn = "Holsted" },
                new PostNummerOgBy { Postnummer = 6682, ByNavn = "Hovborg" },
                new PostNummerOgBy { Postnummer = 6683, ByNavn = "Føvling" },
                new PostNummerOgBy { Postnummer = 6690, ByNavn = "Gørding" },
                new PostNummerOgBy { Postnummer = 6700, ByNavn = "Esbjerg" },
                new PostNummerOgBy { Postnummer = 6705, ByNavn = "Esbjerg Ø" },
                new PostNummerOgBy { Postnummer = 6710, ByNavn = "Esbjerg V" },
                new PostNummerOgBy { Postnummer = 6715, ByNavn = "Esbjerg N" },
                new PostNummerOgBy { Postnummer = 6720, ByNavn = "Fanø" },
                new PostNummerOgBy { Postnummer = 6731, ByNavn = "Tjæreborg" },
                new PostNummerOgBy { Postnummer = 6740, ByNavn = "Bramming" },
                new PostNummerOgBy { Postnummer = 6752, ByNavn = "Glejbjerg" },
                new PostNummerOgBy { Postnummer = 6753, ByNavn = "Agerbæk" },
                new PostNummerOgBy { Postnummer = 6760, ByNavn = "Ribe" },
                new PostNummerOgBy { Postnummer = 6771, ByNavn = "Gredstedbro" },
                new PostNummerOgBy { Postnummer = 6780, ByNavn = "Skærbæk" },
                new PostNummerOgBy { Postnummer = 6792, ByNavn = "Rømø" },
                new PostNummerOgBy { Postnummer = 6800, ByNavn = "Varde" },
                new PostNummerOgBy { Postnummer = 6818, ByNavn = "Årre" },
                new PostNummerOgBy { Postnummer = 6823, ByNavn = "Ansager" },
                new PostNummerOgBy { Postnummer = 6830, ByNavn = "Nørre Nebel" },
                new PostNummerOgBy { Postnummer = 6840, ByNavn = "Oksbøl" },
                new PostNummerOgBy { Postnummer = 6851, ByNavn = "Janderup Vestj" },
                new PostNummerOgBy { Postnummer = 6852, ByNavn = "Billum" },
                new PostNummerOgBy { Postnummer = 6853, ByNavn = "Vejers Strand" },
                new PostNummerOgBy { Postnummer = 6854, ByNavn = "Henne" },
                new PostNummerOgBy { Postnummer = 6855, ByNavn = "Outrup" },
                new PostNummerOgBy { Postnummer = 6862, ByNavn = "Tistrup" },
                new PostNummerOgBy { Postnummer = 6870, ByNavn = "Ølgod" },
                new PostNummerOgBy { Postnummer = 6880, ByNavn = "Tarm" },
                new PostNummerOgBy { Postnummer = 6893, ByNavn = "Hemmet" },
                new PostNummerOgBy { Postnummer = 6900, ByNavn = "Skjern" },
                new PostNummerOgBy { Postnummer = 6920, ByNavn = "Videbæk" },
                new PostNummerOgBy { Postnummer = 6933, ByNavn = "Kibæk" },
                new PostNummerOgBy { Postnummer = 6940, ByNavn = "Lem St" },
                new PostNummerOgBy { Postnummer = 6950, ByNavn = "Ringkøbing" },
                new PostNummerOgBy { Postnummer = 6960, ByNavn = "Hvide Sande" },
                new PostNummerOgBy { Postnummer = 6971, ByNavn = "Spjald" },
                new PostNummerOgBy { Postnummer = 6980, ByNavn = "Tim" },
                new PostNummerOgBy { Postnummer = 6990, ByNavn = "Ulfborg" },
                new PostNummerOgBy { Postnummer = 7000, ByNavn = "Fredericia" },
                new PostNummerOgBy { Postnummer = 7100, ByNavn = "Vejle" },
                new PostNummerOgBy { Postnummer = 7120, ByNavn = "Vejle Øst" },
                new PostNummerOgBy { Postnummer = 7130, ByNavn = "Juelsminde" },
                new PostNummerOgBy { Postnummer = 7140, ByNavn = "Stouby" },
                new PostNummerOgBy { Postnummer = 7150, ByNavn = "Barrit" },
                new PostNummerOgBy { Postnummer = 7160, ByNavn = "Tørring" },
                new PostNummerOgBy { Postnummer = 7171, ByNavn = "Uldum" },
                new PostNummerOgBy { Postnummer = 7173, ByNavn = "Vonge" },
                new PostNummerOgBy { Postnummer = 7182, ByNavn = "Bredsten" },
                new PostNummerOgBy { Postnummer = 7183, ByNavn = "Randbøl" },
                new PostNummerOgBy { Postnummer = 7184, ByNavn = "Vandel" },
                new PostNummerOgBy { Postnummer = 7190, ByNavn = "Billund" },
                new PostNummerOgBy { Postnummer = 7200, ByNavn = "Grindsted" },
                new PostNummerOgBy { Postnummer = 7250, ByNavn = "Hejnsvig" },
                new PostNummerOgBy { Postnummer = 7260, ByNavn = "Sønder Omme" },
                new PostNummerOgBy { Postnummer = 7270, ByNavn = "Stakroge" },
                new PostNummerOgBy { Postnummer = 7280, ByNavn = "Sønder Felding" },
                new PostNummerOgBy { Postnummer = 7300, ByNavn = "Jelling" },
                new PostNummerOgBy { Postnummer = 7321, ByNavn = "Gadbjerg" },
                new PostNummerOgBy { Postnummer = 7323, ByNavn = "Give" },
                new PostNummerOgBy { Postnummer = 7330, ByNavn = "Brande" },
                new PostNummerOgBy { Postnummer = 7361, ByNavn = "Ejstrupholm" },
                new PostNummerOgBy { Postnummer = 7362, ByNavn = "Hampen" },
                new PostNummerOgBy { Postnummer = 7400, ByNavn = "Herning" },
                new PostNummerOgBy { Postnummer = 7430, ByNavn = "Ikast" },
                new PostNummerOgBy { Postnummer = 7441, ByNavn = "Bording" },
                new PostNummerOgBy { Postnummer = 7442, ByNavn = "Engesvang" },
                new PostNummerOgBy { Postnummer = 7451, ByNavn = "Sunds" },
                new PostNummerOgBy { Postnummer = 7470, ByNavn = "Karup J" },
                new PostNummerOgBy { Postnummer = 7480, ByNavn = "Vildbjerg" },
                new PostNummerOgBy { Postnummer = 7490, ByNavn = "Aulum" },
                new PostNummerOgBy { Postnummer = 7500, ByNavn = "Holstebro" },
                new PostNummerOgBy { Postnummer = 7540, ByNavn = "Haderup" },
                new PostNummerOgBy { Postnummer = 7550, ByNavn = "Sørvad" },
                new PostNummerOgBy { Postnummer = 7560, ByNavn = "Hjerm" },
                new PostNummerOgBy { Postnummer = 7570, ByNavn = "Vemb" },
                new PostNummerOgBy { Postnummer = 7600, ByNavn = "Struer" },
                new PostNummerOgBy { Postnummer = 7620, ByNavn = "Lemvig" },
                new PostNummerOgBy { Postnummer = 7650, ByNavn = "Bøvlingbjerg" },
                new PostNummerOgBy { Postnummer = 7660, ByNavn = "Bækmarksbro" },
                new PostNummerOgBy { Postnummer = 7673, ByNavn = "Harboøre" },
                new PostNummerOgBy { Postnummer = 7680, ByNavn = "Thyborøn" },
                new PostNummerOgBy { Postnummer = 7700, ByNavn = "Thisted" },
                new PostNummerOgBy { Postnummer = 7730, ByNavn = "Hanstholm" },
                new PostNummerOgBy { Postnummer = 7741, ByNavn = "Frøstrup" },
                new PostNummerOgBy { Postnummer = 7742, ByNavn = "Vesløs" },
                new PostNummerOgBy { Postnummer = 7752, ByNavn = "Snedsted" },
                new PostNummerOgBy { Postnummer = 7755, ByNavn = "Bedsted Thy" },
                new PostNummerOgBy { Postnummer = 7760, ByNavn = "Hurup Thy" },
                new PostNummerOgBy { Postnummer = 7770, ByNavn = "Vestervig" },
                new PostNummerOgBy { Postnummer = 7790, ByNavn = "Thyholm" },
                new PostNummerOgBy { Postnummer = 7800, ByNavn = "Skive" },
                new PostNummerOgBy { Postnummer = 7830, ByNavn = "Vinderup" },
                new PostNummerOgBy { Postnummer = 7840, ByNavn = "Højslev" },
                new PostNummerOgBy { Postnummer = 7850, ByNavn = "Stoholm Jyll" },
                new PostNummerOgBy { Postnummer = 7860, ByNavn = "Spøttrup" },
                new PostNummerOgBy { Postnummer = 7870, ByNavn = "Roslev" },
                new PostNummerOgBy { Postnummer = 7884, ByNavn = "Fur" },
                new PostNummerOgBy { Postnummer = 7900, ByNavn = "Nykøbing M" },






            };
        
        }
    }
}
